services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EonX\EasyRandom\UuidV4\SymfonyUidUuidV4Generator: ~
    EonX\EasyRandom\UuidV4\RamseyUuidV4Generator: ~

    easy_random.symfony_uuid4:
        alias: 'EonX\EasyRandom\UuidV4\SymfonyUidUuidV4Generator'

    easy_random.ramsey_uuid4:
        alias: 'EonX\EasyRandom\UuidV4\RamseyUuidV4Generator'

    EonX\EasyRandom\Interfaces\RandomGeneratorInterface:
        class: EonX\EasyRandom\RandomGenerator
